# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17b3210ce9a2c26b8610b3a8e9d9d9c903105be974931540d09e04e0dbf73a5aaff1a0cad2707d738c8935b91727c34a693be2e320d40d7d18dfc0dd3b28bacb

test:
  secret_key_base: 6b141b5d70da9a036631281245d09fa74dc47f2b84dc1779db0b0eccab6e99d208ec0aa2565fc35dbfd3b4336de302a12df8226c9952f5c8e4177468c607e483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
